### PR TITLE
mvn multimodule conversion

### PR DESCRIPTION
**Pull request by vprusa**
Sketch.. 

DO NOT MERGE

### CODE REVIEW

**Comment by vprusa** [comment]
Added checkstyle again..
use 
```
mvn clean install -Dcheckstyle.failOnViolation=false
```
it casues warnings now but for failure use
```
mvn clean install -Dcheckstyle.failOnViolation=true
```

Updated some poms dependencies, plugins and related minor changes.

DO NOT MERGE  yet.. I will play with checkstyle plugin and if it will be too annoying I will disable it for good if.

**Comment by vprusa** [comment]
Also i need to squash everything before merge..

**Comment by 433769** [comment]
Looks really good ! Thanks.

**Comment by vprusa** [comment]
> DO NOT MERGE yet.. I will play with checkstyle plugin and if it will be too annoying I will disable it for good if.
> Also i need to squash everything before merge..

**Pull request merged**
